#!/usr/bin/env bash
# provision.sh — OCI ARM VM AD-rotation retry loop
#
# Generated by setup.sh. Do not edit placeholder values directly.
# Re-run setup.sh to regenerate with updated configuration.
#
# Usage:
#   bash provision.sh
#
# Flow:
#   Phase 1 — Apply network/ once (VCN, subnet, IGW). Idempotent, never destroyed.
#   Phase 2 — Loop: destroy + apply instance/ only, rotating across ADs.
#
# Exit codes:
#   0 - SUCCESS: instance provisioned
#   2 - FATAL: service limit / quota reached
#   3 - FATAL: authentication failure
#   4 - FATAL: authorization failure (403 / NotAuthorized)
#   5 - FATAL: invalid parameter (400 / bad OCID or image)

set -uo pipefail

# ---- Configuration (filled in by setup.sh) ----
AD1="{{AD1}}"
AD2="{{AD2}}"
AD3="{{AD3}}"
AD_SLEEP={{AD_SLEEP}}
ROUND_SLEEP={{ROUND_SLEEP}}
RATE_LIMIT_SLEEP=$(( {{ROUND_SLEEP}} * 2 ))
INSTANCE_NAME="ods-instance"
COMPARTMENT_ID="{{COMPARTMENT_OCID}}"
OCI_SHAPE="VM.Standard.A1.Flex"
OCI_MAX_INSTANCES=1
LIMIT_RETRY_MAX=3
LIMIT_RETRY_SLEEP=300
LIMIT_RETRIES=0

# ---- Directory setup ----
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
NETWORK_DIR="${SCRIPT_DIR}/network"
INSTANCE_DIR="${SCRIPT_DIR}/instance"
LOG_FILE="${SCRIPT_DIR}/oci-provision.log"
ROUND=0

# ---- Colors (terminal only — stripped from log file) ----
if [ -t 1 ]; then
  RED='\033[0;31m'
  GREEN='\033[0;32m'
  BLUE='\033[0;34m'
  YELLOW='\033[0;33m'
  BOLD='\033[1m'
  RESET='\033[0m'
else
  RED='' GREEN='' BLUE='' YELLOW='' BOLD='' RESET=''
fi

log() {
  local color="$1"; shift
  local ts
  ts=$(date '+%Y-%m-%d %H:%M:%S')
  local plain="[$ts] $*"
  echo "$plain" >> "$LOG_FILE"
  if [ -n "$color" ]; then
    echo -e "${color}${plain}${RESET}"
  else
    echo "$plain"
  fi
}

fatal() {
  local msg="$1"
  local code="${2:-1}"
  log "$RED" "FATAL: ${msg}"
  echo ""
  echo -e "  ${RED}${BOLD}FATAL ERROR (exit ${code}):${RESET} ${msg}"
  echo ""
  exit "$code"
}

# ---- Error classification ----
classify_error() {
  local output="$1"
  if echo "$output" | grep -qE "Out of host capacity|InsufficientServiceCapacity"; then
    echo "capacity"
  elif echo "$output" | grep -qE "LimitExceeded|service limit|limit exceeded"; then
    echo "limit"
  elif echo "$output" | grep -qE "NotAuthenticated|401|InvalidAuthenticationToken"; then
    echo "auth"
  elif echo "$output" | grep -qE "Forbidden|403|NotAuthorized|not authorized"; then
    echo "forbidden"
  elif echo "$output" | grep -qE "InvalidParameter|400|invalid.*OCID|does not exist in compartment"; then
    echo "invalid"
  elif echo "$output" | grep -qE "TooManyRequests|429|rate limit|Rate limit"; then
    echo "ratelimit"
  elif echo "$output" | grep -qE "InternalError|500|503|internal server error|Service Unavailable"; then
    echo "internal"
  else
    echo "unknown"
  fi
}

# ---- Pre-flight: check existing instance count against quota ----
preflight_check() {
  log "" "Pre-flight: checking existing ${OCI_SHAPE} instance count..."

  local raw cli_exit count
  raw=$(oci compute instance list \
    --compartment-id "$COMPARTMENT_ID" \
    --all 2>/dev/null)
  cli_exit=$?

  if [ "$cli_exit" -ne 0 ]; then
    log "$YELLOW" "Pre-flight: OCI CLI returned error (exit ${cli_exit}). Check ~/.oci/config. Proceeding anyway."
    return
  fi

  if [ -z "$raw" ]; then
    count=0
  else
    count=$(echo "$raw" | python3 -c "
import sys, json
data = json.load(sys.stdin).get('data', [])
print(sum(1 for i in data if i.get('shape') == '${OCI_SHAPE}' and i.get('lifecycle-state') != 'TERMINATED'))
" 2>/dev/null)
    if [ -z "$count" ]; then
      log "$YELLOW" "Pre-flight: could not parse OCI CLI output. Proceeding anyway."
      return
    fi
  fi

  log "$GREEN" "Pre-flight: found ${count} existing ${OCI_SHAPE} instance(s) (non-terminated). Max allowed: ${OCI_MAX_INSTANCES}."

  if [ "$count" -ge "$OCI_MAX_INSTANCES" ]; then
    fatal \
      "Already have ${count}/${OCI_MAX_INSTANCES} ${OCI_SHAPE} instance(s) in non-terminated state. You are at quota. Terminate existing instances first at https://cloud.oracle.com/compute/instances" \
      2
  fi
}

# ---- Terraform init guard ----
needs_init() {
  local dir="$1"
  [ ! -d "${dir}/.terraform" ] && return 0
  [ ! -f "${dir}/.terraform.lock.hcl" ] && return 0
  [ -z "$(find "${dir}/.terraform/providers" -name "terraform-provider-oci*" 2>/dev/null | head -1)" ] && return 0
  return 1
}

if needs_init "$NETWORK_DIR"; then
  echo ""
  echo "  [INFO] Initialising network module..."
  terraform -chdir="$NETWORK_DIR" init || { echo "  [FAIL] terraform init failed for network/"; exit 1; }
  echo ""
fi

if needs_init "$INSTANCE_DIR"; then
  echo ""
  echo "  [INFO] Initialising instance module..."
  terraform -chdir="$INSTANCE_DIR" init || { echo "  [FAIL] terraform init failed for instance/"; exit 1; }
  echo ""
fi

# ---- Banner ----
echo ""
echo -e "${BOLD}============================================================${RESET}"
echo -e "${BOLD}  OCI ARM VM Provisioner — AD Rotation Loop${RESET}"
echo   "  Instance: ${INSTANCE_NAME}"
echo   "  ADs:      ${AD1} / ${AD2} / ${AD3}"
echo   "  AD sleep: ${AD_SLEEP}s   Round sleep: ${ROUND_SLEEP}s"
echo   "  Log:      ${LOG_FILE}"
echo -e "${BOLD}============================================================${RESET}"
echo ""

preflight_check

# ---- Phase 1: Network setup (once) ----
log "" "Phase 1: Applying network module (VCN, subnet, IGW)..."
NET_OUTPUT=$(terraform -chdir="$NETWORK_DIR" apply -auto-approve 2>&1)
NET_EXIT=$?
echo "$NET_OUTPUT" >> "$LOG_FILE"

if [ "$NET_EXIT" -ne 0 ]; then
  echo "$NET_OUTPUT"
  fatal "Network setup failed. Check log for details: ${LOG_FILE}" 1
fi

SUBNET_ID=$(terraform -chdir="$NETWORK_DIR" output -raw subnet_id 2>/dev/null)
if [ -z "$SUBNET_ID" ]; then
  fatal "Could not read subnet_id from network module output." 1
fi
log "$GREEN" "Network ready. Subnet: ${SUBNET_ID}"

# ---- Phase 2: Instance retry loop ----
log "" "Provisioner started. Instance: ${INSTANCE_NAME}"
log "" "ADs: ${AD1} | ${AD2} | ${AD3}"
log "" "Timing: AD_SLEEP=${AD_SLEEP}s  ROUND_SLEEP=${ROUND_SLEEP}s  RATE_LIMIT_SLEEP=${RATE_LIMIT_SLEEP}s"

while true; do
  ROUND=$(( ROUND + 1 ))
  log "" "==============================  Round ${ROUND}  =============================="

  for AD in "$AD1" "$AD2" "$AD3"; do
    log "" "--- Attempting AD: ${AD} ---"

    # Destroy any partial instance state before applying.
    log "" "Running: terraform destroy instance (cleanup partial state)"
    terraform -chdir="$INSTANCE_DIR" destroy -auto-approve \
      -var "availability_domain=${AD}" \
      -var "subnet_id=${SUBNET_ID}" \
      >> "$LOG_FILE" 2>&1 || true

    # Apply instance only
    log "" "Running: terraform apply instance (AD=${AD})"
    TF_OUTPUT=$(terraform -chdir="$INSTANCE_DIR" apply -auto-approve \
      -var "availability_domain=${AD}" \
      -var "subnet_id=${SUBNET_ID}" 2>&1)
    TF_EXIT=$?
    echo "$TF_OUTPUT" >> "$LOG_FILE"

    if [ "$TF_EXIT" -eq 0 ]; then
      log "$GREEN" "SUCCESS: Instance provisioned in ${AD}"
      echo ""
      echo -e "${GREEN}${BOLD}============================================================${RESET}"
      echo -e "${GREEN}${BOLD}  SUCCESS${RESET}"
      echo -e "${GREEN}  Instance '${INSTANCE_NAME}' provisioned in: ${AD}${RESET}"
      echo -e "${GREEN}${BOLD}============================================================${RESET}"
      echo ""
      echo "  Get your public IP:"
      echo "    terraform -chdir=instance output public_ip"
      echo ""
      echo "  Or via OCI CLI:"
      echo "    oci compute instance list-vnics \\"
      echo "      --instance-id \$(terraform -chdir=instance output -raw instance_id) \\"
      echo "      | jq -r '.data[0].\"public-ip\"'"
      echo ""
      echo "  Then:"
      echo "    Edit your .env file and set VM_PUBLIC_IP=<ip>"
      echo "    make ssh   (from repo root)"
      echo ""
      echo "  To tear down everything when done:"
      echo "    terraform -chdir=instance destroy -var availability_domain=<AD> -var subnet_id=${SUBNET_ID}"
      echo "    terraform -chdir=network destroy"
      echo ""
      echo "  Full log: ${LOG_FILE}"
      echo ""
      exit 0
    fi

    ERROR_CLASS=$(classify_error "$TF_OUTPUT")
    log "" "Error class: ${ERROR_CLASS}"

    case "$ERROR_CLASS" in

      limit)
        LIMIT_RETRIES=$(( LIMIT_RETRIES + 1 ))
        if [ "$LIMIT_RETRIES" -ge "$LIMIT_RETRY_MAX" ]; then
          fatal \
            "Service limit reached after ${LIMIT_RETRY_MAX} retries. You are at the Always Free quota for ${OCI_SHAPE}. Check https://cloud.oracle.com/limits and https://cloud.oracle.com/tenancy" \
            2
        fi
        log "$BLUE" "Service limit hit in ${AD} (attempt ${LIMIT_RETRIES}/${LIMIT_RETRY_MAX}). OCI quota may still be settling. Sleeping ${LIMIT_RETRY_SLEEP}s before retrying..."
        sleep "$LIMIT_RETRY_SLEEP"
        ;;

      auth)
        fatal \
          "Authentication failed (401 / NotAuthenticated). Check ~/.oci/config: verify key_file path, fingerprint, tenancy OCID, and user OCID." \
          3
        ;;

      forbidden)
        fatal \
          "Authorization failed (403 / NotAuthorized). Your OCI user lacks permission to manage one or more resources. In OCI Console go to Identity > Policies (root compartment) and ensure your group has: allow group <group> to manage instance-family in tenancy" \
          4
        ;;

      invalid)
        fatal \
          "Invalid parameter (400). Check instance/terraform.tfvars: verify compartment_id and image OCID. Common cause: compartment OCID typo or wrong region." \
          5
        ;;

      ratelimit)
        log "$BLUE" "Rate limited (429 / TooManyRequests). Sleeping ${RATE_LIMIT_SLEEP}s then retrying ${AD} once more before rotating."
        sleep "$RATE_LIMIT_SLEEP"

        log "$BLUE" "Retry after rate limit — AD: ${AD}"
        TF_OUTPUT2=$(terraform -chdir="$INSTANCE_DIR" apply -auto-approve \
          -var "availability_domain=${AD}" \
          -var "subnet_id=${SUBNET_ID}" 2>&1)
        TF_EXIT2=$?
        echo "$TF_OUTPUT2" >> "$LOG_FILE"

        if [ "$TF_EXIT2" -eq 0 ]; then
          log "$GREEN" "SUCCESS: Instance provisioned in ${AD} (after rate limit retry)"
          echo ""
          echo -e "${GREEN}${BOLD}  SUCCESS (after rate limit retry)${RESET}"
          echo -e "${GREEN}  Instance '${INSTANCE_NAME}' provisioned in: ${AD}${RESET}"
          echo ""
          echo "  terraform -chdir=instance output public_ip"
          echo ""
          exit 0
        fi
        log "$BLUE" "Still failing after rate limit retry. Rotating to next AD."
        ;;

      internal)
        log "$BLUE" "OCI internal error (5xx). Sleeping 120s then retrying ${AD} once more."
        sleep 120

        log "$BLUE" "Retry after internal error — AD: ${AD}"
        TF_OUTPUT2=$(terraform -chdir="$INSTANCE_DIR" apply -auto-approve \
          -var "availability_domain=${AD}" \
          -var "subnet_id=${SUBNET_ID}" 2>&1)
        TF_EXIT2=$?
        echo "$TF_OUTPUT2" >> "$LOG_FILE"

        if [ "$TF_EXIT2" -eq 0 ]; then
          log "$GREEN" "SUCCESS: Instance provisioned in ${AD} (after internal error retry)"
          echo ""
          echo -e "${GREEN}${BOLD}  SUCCESS (after internal error retry)${RESET}"
          echo -e "${GREEN}  Instance '${INSTANCE_NAME}' provisioned in: ${AD}${RESET}"
          echo ""
          echo "  terraform -chdir=instance output public_ip"
          echo ""
          exit 0
        fi
        log "$BLUE" "Still failing after internal error retry. Rotating to next AD."
        ;;

      capacity|unknown)
        log "$RED" "No capacity in ${AD} (or unrecognised transient error). Rotating to next AD."
        ;;

    esac

    log "" "Sleeping ${AD_SLEEP}s before next AD..."
    sleep "$AD_SLEEP"

  done  # end AD loop

  log "" "All ADs exhausted in round ${ROUND}. Sleeping ${ROUND_SLEEP}s before round $(( ROUND + 1 ))..."
  sleep "$ROUND_SLEEP"

done  # end round loop
