# instance/terraform.tfvars — Static values for the instance module
#
# Generated by setup.sh. Do not edit {{PLACEHOLDER}} tokens directly.
# Re-run setup.sh to regenerate.
#
# availability_domain and subnet_id are intentionally absent —
# provision.sh passes them dynamically via -var flags.

compartment_id  = "{{COMPARTMENT_OCID}}"
region          = "{{REGION}}"
instance_ocpus  = {{OCPUS}}
instance_memory = {{MEM}}

# SSH public key content — embedded at setup time by setup.sh.
ssh_public_key  = "{{SSH_KEY_CONTENT}}"
