# instance/main.tf — OCI ARM VM instance (VM.Standard.A1.Flex)
#
# Generated by setup.sh. Do not edit {{PLACEHOLDER}} tokens directly.
# Re-run setup.sh to regenerate.
#
# This module creates only the instance. Networking (VCN, subnet, etc.)
# is managed separately by the network/ module and passed in via subnet_id.
#
# availability_domain and subnet_id are passed dynamically by provision.sh
# so the retry loop can rotate across ADs without editing tfvars.
#
# Outputs:
#   - public_ip    (fill into .env VM_PUBLIC_IP after provision)
#   - instance_id

terraform {
  required_providers {
    oci = {
      source  = "oracle/oci"
      version = "~> 5.0"
    }
  }
}

provider "oci" {
  tenancy_ocid = "ocid1.tenancy.oc1..aaaaaaaafzmbug5a3cot4e3q6nhjigj2gorrglld7ul4akivklwxtu5ohzoa"
  region       = var.region
}

# ============================================================
# Image lookup — Ubuntu 22.04 ARM (latest)
# ============================================================
data "oci_core_images" "arm_ubuntu" {
  compartment_id           = var.compartment_id
  operating_system         = "Canonical Ubuntu"
  operating_system_version = "22.04"
  shape                    = "VM.Standard.A1.Flex"
  sort_by                  = "TIMECREATED"
  sort_order               = "DESC"
}

# ============================================================
# Instance — VM.Standard.A1.Flex (Always Free ARM)
# availability_domain and subnet_id are passed dynamically by provision.sh
# ============================================================
resource "oci_core_instance" "main" {
  availability_domain = var.availability_domain
  compartment_id      = var.compartment_id
  shape               = "VM.Standard.A1.Flex"
  display_name        = "ods-instance"

  shape_config {
    ocpus         = var.instance_ocpus
    memory_in_gbs = var.instance_memory
  }

  source_details {
    source_type             = "image"
    source_id               = data.oci_core_images.arm_ubuntu.images[0].id
    # Claim the full 200 GB Always Free block storage allocation on the boot volume.
    boot_volume_size_in_gbs = 200
  }

  create_vnic_details {
    subnet_id        = var.subnet_id
    assign_public_ip = true
    display_name     = "ods-vnic"
    hostname_label   = "odsinstance"
  }

  metadata = {
    ssh_authorized_keys = var.ssh_public_key
  }

  # Delete the boot volume when the instance is destroyed.
  preserve_boot_volume = false
}

# ============================================================
# Outputs
# ============================================================
output "public_ip" {
  value       = oci_core_instance.main.public_ip
  description = "Public IP of the provisioned VM. Copy this into .env as VM_PUBLIC_IP."
}

output "instance_id" {
  value       = oci_core_instance.main.id
  description = "OCID of the provisioned instance."
}
