# instance/variable.tf — Variables for the instance module
#
# Generated by setup.sh. Do not edit {{PLACEHOLDER}} tokens directly.
# Re-run setup.sh to regenerate.
#
# availability_domain and subnet_id have no defaults — they are passed
# dynamically by provision.sh via -var flags so the retry loop can
# rotate across ADs without editing tfvars.

variable "availability_domain" {
  type        = string
  description = "OCI Availability Domain name. Passed dynamically by provision.sh."
}

variable "subnet_id" {
  type        = string
  description = "OCID of the subnet to place the instance in. Read from network module output by provision.sh."
}

variable "compartment_id" {
  type        = string
  description = "Compartment OCID to deploy the instance into."
}

variable "region" {
  type        = string
  description = "OCI region identifier (e.g. us-chicago-1)."
}

variable "instance_ocpus" {
  type        = number
  description = "Number of OCPUs. Always Free tier allows up to 4 OCPUs total across all A1 instances."
}

variable "instance_memory" {
  type        = number
  description = "Memory in GB. Always Free tier allows up to 24 GB total across all A1 instances."
}

variable "ssh_public_key" {
  type        = string
  description = "SSH public key content (not path) for instance access."
}
