# network/terraform.tfvars — Values for the network module
#
# Generated by setup.sh. Do not edit {{PLACEHOLDER}} tokens directly.
# Re-run setup.sh to regenerate.

compartment_id = "{{COMPARTMENT_OCID}}"
region         = "{{REGION}}"
