# network/variable.tf — Variables for the network module
#
# Generated by setup.sh. Do not edit {{PLACEHOLDER}} tokens directly.
# Re-run setup.sh to regenerate.

variable "compartment_id" {
  type        = string
  description = "Compartment OCID to deploy network resources into."
}

variable "region" {
  type        = string
  description = "OCI region identifier (e.g. us-chicago-1)."
}
